### ISSUE TITLE
Missing parenthesis in LL_MPU_ConfigRegion

### ISSUE THREAD

**Issue by carlo-dev-git** [STMicroelectronics/stm32l0xx_hal_driver#8]
In function `LL_MPU_ConfigRegion()` from `stm32l0xx_ll_cortex.h` the following line:
`  WRITE_REG(MPU->RASR, (MPU_RASR_ENABLE_Msk | Attributes | SubRegionDisable << MPU_RASR_SRD_Pos));`

should be fixed with:
`  WRITE_REG(MPU->RASR, (MPU_RASR_ENABLE_Msk | Attributes | (SubRegionDisable << MPU_RASR_SRD_Pos)));`

which is the correct implementation already present in other STM32 MCU HAL drivers.

**Comment by TOUNSTM** [comment]
ST Internal Reference: 176807

**Comment by RJMSTM** [comment]
Fixed in : https://github.com/STMicroelectronics/stm32l0xx_hal_driver/commit/8c56f5d5a5565eb4a67c80e2b2e908938103f415
